# backend/scripts/seed_demo_alerts.py
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

import random
import datetime as dt
from sqlalchemy import func
from backend.app.database import SessionLocal
from backend.app.models import User, Log, Alert  # عدّل المسار لو مختلف عندك

PRIORITIES = ["critical", "high", "medium", "low"]
ANOMALY_TYPES = [
    "impossible_travel",
    "brute_force",
    "data_exfil",
    "privilege_escalation",
    "impossible_session",
]

def main(count: int = 100):
    db = SessionLocal()
    try:
        users = db.query(User).order_by(func.random()).limit(100).all()
        if not users:
            print("No users found. Upload logs first (you already did).")
            return

        logs = db.query(Log).order_by(Log.timestamp.desc()).limit(5000).all()

        created = 0
        for _ in range(count):
            u = random.choice(users)
            lg = random.choice(logs) if logs else None

            detected_at = (
                lg.timestamp if lg and lg.timestamp else dt.datetime.utcnow()
            ) - dt.timedelta(minutes=random.randint(0, 120))

            alert = Alert(
                user_id=u.id,
                anomaly_type=random.choice(ANOMALY_TYPES),
                priority=random.choice(PRIORITIES),
                risk_score=round(random.uniform(0.50, 0.99), 4),
                risk_level=None,  # سيبها فاضية لو مش مستخدمها
                confidence_score=round(random.uniform(0.50, 0.99), 4),
                alert_status="new",
                explanation="Demo alert generated by seed script.",
                detailed_reasons={"demo": True},
                geo_location={"ip": getattr(lg, "source_ip", None)} if lg else None,
                detected_at=detected_at,
            )
            db.add(alert)
            created += 1

        db.commit()
        print(f"Created {created} alerts.")
    finally:
        db.close()

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=100, help="How many alerts to create")
    args = parser.parse_args()
    main(args.count)
